# @package _global_
defaults:
  - _self_
  - paths: default

checkpoint: null
data_dir: "data"
device: cpu
per_task: false
output_dir: null  # Defaults to checkpoint_dir/evaluation_results
batch_size: 32
